### ISSUE TITLE
Nice work!  Can the wifi be upgraded to Broadcom?

### ISSUE THREAD

**Issue by gatorback** [swazen/HP-Elitebook-x360-1040-G7-opencore-Ventura-Hackintosh#1]
Can the wifi be removed and replaced with Broadcom?  
https://i.ebayimg.com/images/g/bjsAAOSwKlxeIY5R/s-l500.jpg

Apparently necessary for 'AirDrop'

**Comment by swazen** [comment]
thank's for your comment!
I don't know but this hack works with other HP laptop...
I don't use Airdrop
